# Generated by Django 4.0.1 on 2022-02-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinformation',
            old_name='for_100gm',
            new_name='spec_info',
        ),
        migrations.RenameField(
            model_name='productinformation',
            old_name='for_16gm',
            new_name='specs',
        ),
        migrations.RemoveField(
            model_name='productinformation',
            name='nutrition_information',
        ),
    ]
